# Generated by Django 2.2.5 on 2019-09-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_python', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='ExercisesCode',
            new_name='ExerciseCode',
        ),
    ]
