# Generated by Django 2.2.5 on 2019-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_python', '0003_exercise_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='punkty'),
        ),
    ]
