# Generated by Django 2.2.5 on 2019-09-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_python', '0004_auto_20190924_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='points',
            new_name='award_points',
        ),
        migrations.AddField(
            model_name='points',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn_python.Exercise', verbose_name='zadanie'),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
    ]
