# Generated by Django 2.2.5 on 2019-09-24 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn_python', '0005_auto_20190924_1528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='points',
            unique_together={('user', 'exercise')},
        ),
    ]
