# Generated by Django 2.2.5 on 2019-09-26 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn_python', '0007_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('from_user', 'to_user')},
        ),
    ]
