# Generated by Django 2.2.5 on 2019-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_python', '0008_auto_20190926_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='tytuł'),
        ),
    ]
